/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.usuario;

import controller.CategoriaTransacaoController;
import controller.CategoriaTransacaoController;
import controller.TransacaoController;
import controller.TransacaoController;
import controller.UsuarioController;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.CategoriaTransacao;
import model.Transacao;
import model.Usuario;
import view.categoriaTransacao.Categorias;
import view.categoriaTransacao.CriarCategoria;
import view.categoriaTransacao.EditarCategoria;
import view.categoriaTransacao.Orcamento;
import view.transacao.CadastroTransacao;
import view.transacao.Extrato;
import view.transacao.Relatorio;
import view.transacao.Transacoes;


/**
 *
 * @author Rodrigo
 */
public class MeuEscritorio extends javax.swing.JFrame {

    /**
     * Creates new form MeuEscritorio
     */
    
    public static Usuario usuarioLogado;
    
    public MeuEscritorio(Usuario usuarioLogado){
        
        
        
        initComponents();
        try{
            this.usuarioLogado = usuarioLogado;
            menuUsuario.setLabel(usuarioLogado.nome);
            Image icon = Toolkit.getDefaultToolkit().getImage("src/Image/money_dollar.png");
            setIconImage(icon);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, "Erro!", 0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuUsuario = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem9.setText("jMenuItem9");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meu Escritório");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(800, 600));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/house.png"))); // NOI18N
        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/coins.png"))); // NOI18N
        jMenuItem1.setText("Nova Transação");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/page_white_paste.png"))); // NOI18N
        jMenuItem2.setText("Nova Categoria");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cog.png"))); // NOI18N
        jMenu3.setText("Ferramentas");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/application.png"))); // NOI18N
        jMenuItem8.setText("Visualizar Transações");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem11.setIcon(new javax.swing.ImageIcon("/media/sda3/netbeans/projeto 0.99/src/Image/application.png")); // NOI18N
        jMenuItem11.setText("Visualizar Categorias");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon("/media/sda3/netbeans/projeto 0.99/src/Image/cart_edit.png")); // NOI18N
        jMenuItem12.setText("Extrato");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuItem13.setIcon(new javax.swing.ImageIcon("/media/sda3/netbeans/projeto 0.99/src/Image/chart_bar.png")); // NOI18N
        jMenuItem13.setText("Relatorio");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem14.setIcon(new javax.swing.ImageIcon("/media/sda3/netbeans/projeto 0.99/src/Image/coins.png")); // NOI18N
        jMenuItem14.setText("Orçamento");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/information.png"))); // NOI18N
        jMenu4.setText("Ajuda");
        jMenuBar1.add(jMenu4);

        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        menuUsuario.setText("Usuario");
        menuUsuario.setHideActionText(true);
        menuUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        menuUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuUsuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        jMenuItem6.setText("Editar Perfil");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItem6);

        jMenuItem15.setIcon(new javax.swing.ImageIcon("/media/sda3/netbeans/projeto 0.99/src/Image/group.png")); // NOI18N
        jMenuItem15.setText("Contas vinculadas");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItem15);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/door_open.png"))); // NOI18N
        jMenuItem3.setText("Deslogar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItem3);

        jMenuBar1.add(menuUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Transacoes visualizarTransacoes = new Transacoes();
        jDesktopPane1.add(visualizarTransacoes);
        visualizarTransacoes.setVisible(true);
        try{
            visualizarTransacoes.setMaximum(true);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.setVisible(false);
        telaIn.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CriarCategoria novaCategoria = new CriarCategoria();
        jDesktopPane1.add(novaCategoria);
        try{
        novaCategoria.setMaximum(true);
        }catch(Exception e){
            
        }
        novaCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadastroTransacao novaTransacao = new CadastroTransacao();
        jDesktopPane1.add(novaTransacao);
        try{
        novaTransacao.setMaximum(true);
        }catch(Exception e){
            
        }
    
        novaTransacao.setVisible(true);
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        EditarPerfil modificarUsuario = new EditarPerfil();
        jDesktopPane1.add(modificarUsuario);
        try{
        modificarUsuario.setMaximum(true);
        }catch(Exception e){
            
        }
        modificarUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Categorias categorias = new Categorias();
        jDesktopPane1.add(categorias);
        try {
            categorias.setMaximum(true);
            categorias.setVisible(true);
        } catch (PropertyVetoException ex) {
            
        }
        
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        Extrato extrato = new Extrato();
        jDesktopPane1.add(extrato);
        try {
            extrato.setMaximum(true);
        } catch (PropertyVetoException ex) {

        }
        extrato.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        Relatorio relatorio = new Relatorio();
        jDesktopPane1.add(relatorio);
        try {
            relatorio.setMaximum(true);
        } catch (PropertyVetoException ex) {

        }
        relatorio.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        Orcamento orcamento = new Orcamento();
        jDesktopPane1.add(orcamento);
        try {
            orcamento.setMaximum(true);
        } catch (PropertyVetoException ex) {

        }
        orcamento.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        ContasVinculadas contas = new ContasVinculadas();
        MeuEscritorio.jDesktopPane1.add(contas);
        try {
            contas.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MeuEscritorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        contas.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed
    public void setTelaInicial(TelaInicial tela){
        this.telaIn = tela;
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables
    private TelaInicial telaIn;
}      
