/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.transacao;

import controller.TransacaoController;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Transacao;
import view.ButtonColumn;
import view.RenderizadorTransacao;
import view.usuario.MeuEscritorio;
import view.usuario.TelaInicial;

/**
 *
 * @author victor
 */
public class Transacoes extends javax.swing.JInternalFrame {


    private TransacaoController transacaoController;
    
    public Transacoes() {
        initComponents();
        preencheTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jButton1.setText("Criar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Transações");

        jTable1.setBackground(new java.awt.Color(254, 254, 254));
        jTable1.setDefaultRenderer(Object.class, new RenderizadorTransacao());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Despesa/Provento", "Descrição", "Valor", "Categoria", "Recorrencia", "Data de inserçao", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    
public void preencheTabela(){
        
        final DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            transacaoController = new TransacaoController();
            Iterator it = transacaoController.toList(MeuEscritorio.usuarioLogado.email).iterator();
            Transacao t;
            
            while(it.hasNext()){
                t = (Transacao) it.next();
                model.addRow(new Object[]{t.id,t.tipoTransacao,t.descricao,t.valor,t.categoria,
                    t.tipoRecorrencia,t.dataInsercao,"Atualizar", "Deletar"});
            }
            
            Action delete = new AbstractAction(){
                public void actionPerformed(ActionEvent e){
                    JTable table = (JTable)e.getSource();
                    int modelRow = Integer.valueOf( e.getActionCommand() );
                    
                    int coluna = 0;
                    Object obj = jTable1.getValueAt(jTable1.getSelectedRow(),coluna); 
                    int id = (Integer) obj;
                    try {
                        transacaoController.remover(id, MeuEscritorio.usuarioLogado.email);
                        JOptionPane.showMessageDialog(null, "Transacao removida com sucesso");
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }
                    
                    
                    ((DefaultTableModel)table.getModel()).removeRow(modelRow);
                }
            };
            
           Action atualizar = new AbstractAction(){
                public void actionPerformed(ActionEvent e){
                    JTable table = (JTable)e.getSource();
                    int modelRow = Integer.valueOf( e.getActionCommand() );
                    Transacao t = null;
                    
                    int coluna = 0;
                    Object obj = jTable1.getValueAt(jTable1.getSelectedRow(),coluna); 
                    int id = (Integer) obj;
                    try {
                        EditarTransacao editar = new EditarTransacao(id);
                        MeuEscritorio.jDesktopPane1.add(editar);
                        editar.setMaximum(true);
                        editar.setVisible(true);
                        dispose();
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }

                }
            };
            
            ButtonColumn buttonColumn = new ButtonColumn(jTable1,atualizar, 7);
            ButtonColumn buttonColumn2 = new ButtonColumn(jTable1,delete, 8);
            buttonColumn.setMnemonic(KeyEvent.VK_D);
            buttonColumn2.setMnemonic(KeyEvent.VK_D);
            
        } catch (Exception e) {
        }
    }




}
